lang: en-US
title: Kevin Casas
description: Software Engineer | Java | Kotlin | Python | Full Stack
logo: /assets/img/profile.JPG
show_downloads: false
#theme: jekyll-theme-minimal
remote_theme: "dracula/gh-pages"
plugins:
  - jekyll-remote-theme
